version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: carteira
    ports:
      - "13306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 5s
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: codeigniter-app
    ports:
      - "8080:80"  # Expondo a aplicação na porta 8080
    volumes:
      - .:/var/www/html  # Monta o diretório local no contêiner
    depends_on:
      - db  # Garante que o DB esteja disponível antes do web
    environment:
      - DB_HOST=db
      - DB_PORT=13306
      - DB_DATABASE=carteira
      - DB_USERNAME=root
      - DB_PASSWORD=""
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost"]
      interval: 10s
      retries: 5
